VIEW_ATTRIBUTES = 5
VIEW_ID = 0
ABSOLUTE_ROTATION = 1
ABSOLUTE_TRANSLATION = 2
DESCRIPTORS = 3
KEYPOINTS = 4


CONNECTION_ATTRIBUTES = 6
VIEW_ID_1 = 0
VIEW_ID_2 = 1
RELATIVE_ROTATION = 2
RELATIVE_TRANSLATION = 3
SOURCE_POINTS = 4
DESTINATION_POINTS = 5
