VIEW_ATTRIBUTES = 5
VIEW_ID = 0
ABSOLUTE_ROTATION = 1
ABSOLUTE_TRANSLATION = 2
DESCRIPTORS = 3
KEYPOINTS = 4

viewAttributesDict = {
'VIEW_ID': VIEW_ID,
'ABSOLUTE_ROTATION': ABSOLUTE_ROTATION,
'ABSOLUTE_TRANSLATION': ABSOLUTE_TRANSLATION,
'DESCRIPTORS': DESCRIPTORS,
'KEYPOINTS': KEYPOINTS
}

CONNECTION_ATTRIBUTES = 6
VIEW_ID_1 = 0
VIEW_ID_2 = 1
RELATIVE_ROTATION = 2
RELATIVE_TRANSLATION = 3
SOURCE_POINTS = 4
DESTINATION_POINTS = 5

connectionAttributesDict = {
	'VIEW_ID_1': VIEW_ID_1,
	'VIEW_ID_2': VIEW_ID_2,
	'RELATIVE_ROTATION': RELATIVE_ROTATION,
	'RELATIVE_TRANSLATION': RELATIVE_TRANSLATION,
	'SOURCE_POINTS': SOURCE_POINTS,
	'DESTINATION_POINTS': DESTINATION_POINTS
}
